# Site settings
title: James Sha Personal Site
email: jamessha78@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
    Pretty self descriptive if you ask me
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jamessha78.github.io" # the base hostname & protocol for your site
github_username:  jamessha78

# Build settings
markdown: kramdown

# Testing
port: 5000
