# Site settings
title: James Sha
email: jamessha.personal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My personal site
baseurl: "jamessha.github.io" # the subpath of your site, e.g. /blog/
url: "http://jamessha.github.io" # the base hostname & protocol for your site
github_username:  jamessha

# Build settings
markdown: kramdown

# Testing
port: 5000
